version: 2

models:
  - name: customers
    description: This model provides a comprehensive view of customer information,
      including their first and most recent orders, total number of orders, and lifetime
      value. It combines data from multiple source tables (customers, orders, payments,
      and signups) to create a centralized customer profile. This model is essential
      for understanding customer behavior and identifying high-value customers, which
      can inform marketing strategies and business decisions.
    config:
      tags: ["PII"]

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

    meta: {}
  - name: orders
    description: This model represents the orders table, providing a comprehensive
      view of all orders placed, including payment details. It serves the finance
      team by consolidating order and payment data to enable analysis of order performance,
      payment methods, and overall revenue. The model performs key transformations,
      such as calculating the total amount, credit card amount, coupon amount, bank
      transfer amount, and gift card amount for each order, allowing for deeper analysis
      of payment trends and customer behavior.
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

    meta: {}
  - name: returned_orders
    description: This model represents all orders that have been returned or are pending
      return. It serves the finance team by providing a comprehensive view of the
      company's returned orders, which is important for understanding revenue, refunds,
      and inventory management. The model filters the orders table to include only
      those with a status of 'return_pending' or 'returned'.
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
    meta: {}
