version: 2

models:
  - name: customers
    description: This model represents a comprehensive view of customer information,
      including their basic details, order history, payment data, and signup information.
      It serves as a central source for understanding customer lifecycle and behavior,
      enabling data analysts to derive insights that support marketing, sales, and
      customer success initiatives. Key transformations include calculating the number
      of orders, total lifetime value, and first and most recent order dates for each
      customer.
    config:
      tags: ["PII"]

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

  - name: orders
    description: This model represents the orders table, which contains basic information
      about orders, as well as derived facts about the payments associated with each
      order. The model aggregates payment data, such as the total amount paid by credit
      card, coupon, bank transfer, and gift card, to provide a comprehensive view
      of the order and payment details. This information can be used by data analysts
      and other data consumers to understand the financial aspects of the company's
      orders and support various business analysis and reporting requirements.
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: returned_orders
    description: This model represents all orders that have been returned or are pending
      return. It provides a consolidated view of the order return status, which is
      useful for analyzing the company's returns and refunds processes. The model
      filters the orders table to only include rows where the order status is 'return_pending'
      or 'returned', giving data consumers a clear picture of the returned orders.
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
