version: 2

models:
  - name: customers
    description: This model represents the customer data, including basic customer
      information, their order history, and payment details. It serves as a central
      source of customer-related data for data analysts and other data consumers to
      understand customer behavior and performance. The model aggregates and joins
      data from multiple source tables, such as customer information, orders, payments,
      and signup details, to provide a comprehensive view of each customer's lifecycle
      and value to the business.
    config:
      tags: ["PII"]

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

    meta: {}
  - name: orders
    description: This model represents the orders table, which contains basic information
      about orders, as well as derived metrics based on payment data. It serves the
      finance domain and provides a central source of truth for order-related data.
      The key transformations performed include calculating the amount paid by different
      payment methods (credit card, coupon, bank transfer, gift card) and the total
      amount for each order.
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

    meta: {}
  - name: returned_orders
    description: This model contains all returned orders from the orders table. It
      filters the orders table to include only orders with a status of 'return_pending'
      or 'returned', providing a centralized view of all returned orders. This model
      can be used by finance teams to analyze returned orders and understand the impact
      on the business.
    config:
      tags: ["finance"]

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
    meta: {}
